apiVersion: v1
kind: Service
metadata:
  name: {{ include "onix-adapter.fullname" . }}
  namespace: {{ .Values.config.namespace }}
  labels:
    {{- include "onix-adapter.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.container.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "onix-adapter.selectorLabels" . | nindent 4 }}
